---
- hosts: all
  sudo: yes
  gather_facts: no

  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python

  tasks:

  - name: Add an Apt signing key to a specific keyring file
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add an Apt repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present
      update_cache: yes

  - name: Install docker-ce
    apt:
      name: docker-ce
      update_cache: yes

  - name: Copy loadbalancer to server
    copy:
      src: ../apps/lb_nginx
      dest: /home/ubuntu